### ISSUE TITLE
SMB shares no longer available from some app's save dialogs

### ISSUE THREAD

**Issue by mikehaertl** [linuxmint/nemo#1521]
I'm not sure if this is the right place to report this, so please let me know if it should be moved elsewhere. But as SMB shares are managed by Nemo I thought it's probably related.

For some time now (1-2 weeks?) I no longer can navigate to SMB shares from the "Save As" dialogs that opens when saving files from certain applications. Affected are for example Thunderbird or Google Chrome. This worked before, even though I always first had to open the share from Nemo in order to make the share visible in the save dialog. Not all applications are affected, though. For example LibreOffice still shows my shares.

I'm not sure, how these dialogs are generated (e.g. by the Mint system or by the app itself). But as both, Chrome and Thunderbird, show a slightly modified dialog lately, I assume that it's part of the system:

![download_dialog](https://user-images.githubusercontent.com/675062/27075727-54d299e4-502b-11e7-9ad9-e4cbd31efd68.png)

In contrast, here's the "old" dialog from LibreOffice, where you can still see "shared auf dd-wrt" SMB share:

![download_dialog_share](https://user-images.githubusercontent.com/675062/27075973-183339d4-502c-11e7-858a-73acce0f0e00.png)

My Versions:

* Mint 18.1
* Nemo 3.3.2
* Chrome 59.0.3071.104 
* Thunderbird 52.1.1
* LibreOffice 5.1.6.2

**Comment by mikehaertl** [comment]
@mtwebster Any comment on this? Or could you let me know where I should report this if this is not related to nemo?

As said above, this suddenly stopped working, so I don't believe it has to do with Chrome/Thunderbird as this would be a big coincidence if it stops working for both at the same time.

**Comment by devsware** [comment]
Same problem here.
I'm using Mint 18.1 and my colleague uses Mint 17 and in both of them network shares or network related bookmarks aren't displayed on "Save" and "Open" dialogs.

Other location and bookmarks referring to the local machine are correctly displayed.

I've also tried to mount the network shares before opening the dialog (some are public, some other requires username/password login) but this doesn't help.

I checked and found this behavior on Google Chrome, Firefox, Vivaldi and Opera and all of them presents the same dialog without network resources.

Strangely, if I use Chromium, the "Open" and "Save as" dialogs are different from the "browser ones" (in fact it is the "same old dialog") and displays the network resources.

The same "old" dialog appears when using Atom.io editor, Libre Office and other softwares, so it seems something tied to some program in particular (mainly browsers?) that opens a "different kind" of dialog.

Do anyone know if this behavior can be blocked and force every software to use the "standard" open/save dialog that displays network resources?

**Comment by mtwebster** [comment]
Nemo doesn't have anything to do with these dialogs.

Generally they're provided by whatever app toolkit was used to create them.  That's typically Gtk3, Gtk2, or maybe QT.

Doing some testing here, I discovered Nemo itself was broken when using the right-click move-to/copy-to Browse dialogs.  Digging a bit, I discovered, at least in gtk2/gtk3, file dialogs like this must be explicitly told to show non-local locations - this isn't a security decision, but potentially simplifies file handling - the program only has to work with file paths, rather than uris (like `smb://foo/bar`)

I've fixed nemo here: https://github.com/linuxmint/nemo/commit/4800cd9aa522e153c726dbedaa293ae1017289d6

But unfortunately, any programs that generate this sort of dialog probably have the same issue, and maybe like me, they never noticed it, or, possibly, they've altered the behavior of their dialogs one way or the other on purpose.

I can confirm the issue in firefox and chrome, but as far as I can see, it'll be up to them to fix it as well.

**Comment by mikehaertl** [comment]
> Digging a bit, I discovered, at least in gtk2/gtk3, file dialogs like this must be explicitly told to show non-local locations

@mtwebster Thanks for the heads-up and sorry for bugging. But I'm still surprised that this simultaneously stopped working for a couple of applications at once. I mean, it's very unlikely, that they all changed their calls for opening the dialogs, right?

Do you happen to know if there maybe was any change in the defaults of the lower level Gtk3/2 or Qt lib?

**Comment by mtwebster** [comment]
Not that I'm aware of.. this could be a conscious change on their parts (security reasons?)... it could be they changed how they create the dialog and missed this detail of having to explicitly enable remote files - this has happened before.  Program X used to make their own dialog.. and in the interests of easier maintenance, they decided to just use a toolkit stock dialog instead.

I can't think of anything in a user's *system* that would cause this to become an issue - particularly since we can check other programs and most of them are unchanged.

**Comment by mikehaertl** [comment]
Ok, thanks. To bad there's no fix on the mint side.

I'm still not sure how to proceed now. As completely different applications are affected I wouldn't know where to report this issue. I somehow feel they'd all respond with "not caused by us".

**Comment by mtwebster** [comment]
I understand - I'm not convinced myself yet.

If you run
```
ls -la /run/user/`id -u`/gvfs
```

Does it list your shares there?

Who owns them?  It should be your user.

**Comment by devsware** [comment]
Well, I agree that the problem happened simultaneously on non-related programs (I could understand the link between Firefox and Thunderbird, but also Chrome, Vivaldi and Opera showed the same problem at the same time), so maybe it's related to the toolkit they use to open the open/save dialog, as @mtwebster stated).

If it could be of any help, an user-based workaround is to create a symbolic link to /run/user/UID/gvfs somewhere (i.e. on your home folder and changing UID to your real user id) and then bookmark that.

In my test, this bookmark was correctly shown on the open/save dialog and I could navigate through the network shares, but this solution is neither the best nor the most elegant (but it works... so... ^_^')

**Comment by mikehaertl** [comment]
@mtwebster The file belong to my user and my group:

```
drwx------ 1 mike mike   0 Sep 19  2016 smb-share:server=dd-wrt,share=shared
```

But note, that I first have to access the share from Nemo. Otherwhise there are no files in the `gvfs` directory.

**Comment by mikehaertl** [comment]
As this issue persists I've looked for a better workaround and found autofs. This works like a charm and for me brings back the initial functionality. I can now save to my network drive from any save dialog again.

For those interested, here's the setup:

```
# As root:
apt install autofs cifs-utils
mkdir /etc/autofs.master.d /media/smb
echo '/media/smb  /etc/auto.cifs-shared --ghost' > /etc/autfs.master.d/smb.autofs
echo 'somename -fstype=cifs,password=,uid=1000,vers=1.0 ://192.168.1.1/shared' > /etc/auto.cifs-shared
service autfs restart
```
Now the smb share named `shared` from the smb server under `192.168.1.1` is available under `/media/smb/somename`. It will be automounted, each time the directory is accessed. I've added this directory to my nautilus bookmarks and now can access it from everywhere. As a bonus it gets unmounted automatically after some timeout.

The options can be tweaked, of course. For example I had to add `vers=1.0` to make it work with an older dd-wrt firmware.
