### ISSUE TITLE
Error when copying files: "The name was not provided by any .service file"

### ISSUE THREAD

**Issue by schorschii** [linuxmint/nemo#2345]
```
 * Nemo version (nemo --version): 4.0.6
 * Is issue with desktop or windowed nemo? both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 19.1
 * Graphics hardware *and* driver used: NVIDIA proprietary driver v435
 * 32 or 64 bit: 64 bit
 ```

**Issue**
Sometimes when copying files from a remote file system (mounted via gvfs) there comes up an error like this: "The name :1.6033 was not provided by any .service file". The number after ":1." seems to vary, maybe a PID. It's the most curious error I've seen in my time using Linux, because I have no clue what this message means.
![Bildschirmfoto vom 2020-04-02 20-36-27](https://user-images.githubusercontent.com/17480795/78292157-e76b5700-7526-11ea-9c9c-08b79352dfab.png)

- While I'm unable to copy via Nemo, doing the same copy in terminal via cp is possible.
- Additionally, this error appears not every time. I can't figure out a pattern.
- It is **not** related to specific hosts of mine because it appears on my private computer and on my computer at work, connecting with different remote servers.
- After a restart, the issue is gone for some time.

**Steps to reproduce**
1. Mount a remote file system via Nemo: "File" -> "Connect to server" (I tested it with SSH, but the type seems not to be important).
2. Wait some time. It mostly works fine in when testing it directly after connection started.
2. Copy a file from this share to your desktop or anywhere else -> maybe this message appears.  
   The error seems to only appear when dragging a file from one Nemo window into another (e.g. from window to desktop). 
   At the same time, when doing drag & drop inside the same window (e.g. to Desktop bookmark), the error does not appear.

**Expected behaviour**
File copy should start.

**Other information**
My computers often run 24/7. I think it's possible that many users did not notice this issue because they are shutting down their machine every day. As described above, a restart also temporary fix the problem for me.

I know it's strange, please tell me what additional info or logs I can append on this issue. I hope you can fix this, it's annoying. Thanks!

**Comment by mtwebster** [comment]
Is there anything in your ~/.xsession-errors log when this occurs?

Can you run nemo from a terminal with some debugging enabled:

```
nemo --quit
G_MESSAGES_DEBUG=all nemo
```

I know you mentioned this occurred regardless of connection type, but for ssh, you could try setting a `ServerAliveInterval` in your ssh config:

in `~/.ssh/config` (create if you need to) put:

```
Host *
  ServerAliveInterval 120
```
That would have the server send a ping every 120 seconds to keep the connection alive.  This may or may not work - I'm not sure what the problem actually is but it's perhaps worth a shot.

**Comment by schorschii** [comment]
Thanks for the suggestions. Running Nemo with debugging enabled produces this output on start. There is no output when the error message appears.
```
(nemo:101388): Gtk-DEBUG: 13:10:57.802: Connecting to session manager
(nemo:101388): Gtk-DEBUG: 13:10:57.802: Registering client 'org.Nemo' ''
(nemo:101388): Gtk-DEBUG: 13:10:57.803: Registered client at '/org/gnome/SessionManager/Client171'
Initializing nemo-image-converter extension
```

I added the `ServerAliveInterval` to my ssh config and rebooted recently. I'll get back to you as soon as it occurs again.

**Comment by schorschii** [comment]
Got the error message today again with `ServerAliveInterval` in my ssh config. My computer was only suspended last night (not powered off).
```
The name :1.82 was not provided by any .service files
```

**New hint: after killing nemo it temporarily works again. This means a complete reboot ist not needed.**
```
killall nemo
killall nemo-desktop
G_MESSAGES_DEBUG=all nemo
```

**Comment by schorschii** [comment]
The error occurred today when connecting to a server:
![Bildschirmfoto vom 2020-04-22 09-55-36](https://user-images.githubusercontent.com/17480795/79955893-b2945500-847f-11ea-91e1-5b87bf957fa9.png)
After restarting nemo, I was able to connect to the same server.

**Comment by Atalanttore** [comment]
Same problem in Nemo 4.8.6 on Linux Mint 20.1 when moving files from an SMB share to the desktop.

![Verschieben_auf_Schreibtisch](https://user-images.githubusercontent.com/628474/111072536-424d5280-84db-11eb-909c-05afc6c77c04.png)

**Comment by Atalanttore** [comment]
Same problem in Nemo 4.8.6 on Linux Mint 20.1 when moving files from an Android smartphone connected via USB to the desktop.

![Verschieben_auf_Schreibtisch](https://user-images.githubusercontent.com/628474/111072696-fe0e8200-84db-11eb-94f7-cc1294a2655e.png)

**Comment by Devonavar** [comment]
This issue is likely not in Nemo, but I'm sharing info here in hopes we can identify where the bug exists and re-file it in an appropriate place.  I'm seeing this error with Sound Juicer when mounting CDs.  There's lots of other reports of the error when mounting USB keys, phones or other devices.
![Screenshot from 2022-01-11 23-19-07](https://user-images.githubusercontent.com/5544992/149081702-5fd74f0b-44d2-45f0-88bb-fbdd78b58684.png)
.

The best clue I can find is here, which points at "Auto Mount" as the culprit, without any other sources cited:  https://forums.raspberrypi.com/viewtopic.php?t=293531

So ... who knows what package Debian uses for automounting?  Can we track this any further?

**Comment by schorschii** [comment]
The message seems to be generated in dbus. I grepped all files inside my system and found the string in the dbus-daemon:
```
georg@T-800:~$ LANG=C grep -R "was not provided by any .service file" /usr 2>/dev/null
Binary file /usr/lib/dbus-1.0/dbus-daemon-launch-helper matches
Binary file /usr/bin/dbus-daemon matches

georg@T-800:~$ strings /usr/bin/dbus-daemon | grep ".service file"
The service file is incorrect or does not have all required attributes
The new service name "%s" of service file "%s" is already in cache, ignoring
The name %s was not provided by any .service files
Can't stat the service file
invalid service file: key=value before [Section]
No "%s" key in .service file
```

**Comment by Devonavar** [comment]
I think dbus is another intermediary; it's a means of inter-process (and inter-program) communication.  Presumably all of our various mouting programs (Nemo, AudioJuicer etc.) are making an underlying call (a system call?) to some other program (cp? stat?), using dbus to make the call.  We need to figure out which program is being called, and why it is failing (presumably it has something to do with automount).  I'm with you, I don't have enough knowledge of how all the parts of linux interact to know where to look.

**Comment by schorschii** [comment]
I found something interesting [here](https://gitlab.freedesktop.org/dbus/dbus/-/issues/317).

> This is unlikely to be a dbus bug. If a D-Bus client tries to communicate with the connection whose unique name is :1.1079, and that connection has exited, then it is correct to report that error. This is the D-Bus equivalent of trying to signal process ID 1234 and finding that it has exited, or trying to read a file and finding that it has been deleted.
The thing to look into here is probably why :1.1079 has disappeared from the bus. From your log snippet, it looks as though it might be the gvfsd process; maybe it crashed?

Seems that my idea of a process ID was not that wrong.

**Comment by schorschii** [comment]
And another additional info I observed just now: the error seems to only appear when dragging a file from one Nemo window into another (e.g. from window to desktop). At the same time, when doing drag & drop inside the same window (e.g. to Desktop bookmark), the error does not appear.

**Comment by Devonavar** [comment]
That link flags gvfsd (obtained from using dbus-monitor).  I'm not familiar enough with dbus-monitor to figure out the appropriate watch-string to confirm, but it seems like maybe we need to file the bug with gvfsd.  It would be useful if someone could get a dbus log using nemo (I'm here because I have the same issue with sound-juicer, but I'm pretty off-topic for a nemo bug).

**Comment by baradhili** [comment]
ok I found this one after getting frustrated as to why nemo regularly failed connecting the a sftp account.. tried the killall thing and found ti works..  - will leave the terminal running and see if I get anything useful when it fails..

**Comment by LordSimal** [comment]
as @schorschii already mentioned the problem only appears when you try to copy (either drag&drop or ctrl+c => ctrl+v) from a nemo window to the desktop.
It does not appear (and therefore work) when copying from one memo window to another.
In my case it was a samba share folder which I wanted to copy a file to my desktop.

**Comment by baradhili** [comment]
Nope I was getting it copying between remote server folder to local machine folder.. between Nemo windows

**Comment by Moilleadoir** [comment]
Just happened for me when trying to access Android phone after plugging it in and changing to File Transfer. Simply closing Nemo and opening it again solves the problem.

**Comment by porkpig1** [comment]
> Just happened for me when trying to access Android phone after plugging it in and changing to File Transfer. Simply closing Nemo and opening it again solves the problem.

Same for me

**Comment by yoosefi** [comment]
Happens to me all the time. I work around this by doing "Open in Terminal" via context menu in the SFTP folder and doing `cp file ~/Desktop`

**Comment by rfnxinger** [comment]
Same happens with my Zorin installation!
But HEre the error massage is about "The Name 1.106 could ..."
![grafik](https://user-images.githubusercontent.com/31359191/222797245-4a45fa61-b234-412e-88f3-f9bedac89956.png)

None of the here given solutions succeeded.

Can anybody please help on this?

**Comment by abbyslab** [comment]
> Just happened for me when trying to access Android phone after plugging it in and changing to File Transfer. Simply closing Nemo and opening it again solves the problem.

Just plugging in my android phone and pressing authorise on the phone does this. No other action needed.

**Comment by nerozero** [comment]
Experiencing same issue after waking up PC and trying to access previously opened sftp resource. Fixed by restarting nemo.
> killall -QUIT nemo

**Comment by ResCXsention** [comment]
I'm suffering from this issue as well when attempting to transfer from an Android device of mine; Nemo 5.2.4. Like the aforementioned, I am unable to drag directly out of the window, but, unlike the aforementioned, a simple restart of Nemo did not fix the problem. Up to now, I've been bypassing for now the issue by simply moving files into a different folder before placing it in the appropriate location.
