### ISSUE TITLE
Several issues including crash when moving files and using the undo functionality

### ISSUE THREAD

**Issue by Neher-Veem** [linuxmint/nemo#3157]
```
 * Nemo version: 5.6.1 (2023-08-05 EDIT: 5.6.4 still reproducing the same behaviors)
 * Is issue with desktop or windowed nemo? windowed nemo, it happens in any directory including desktop
 * Distribution - (Linux Mint 21.1)
 * Graphics hardware *and* driver used: Intel HD Graphics 4000 / i915
 * 32 or 64 bit : 64 bit
 ```

**Issue**

**First of all this is the working directory scenario for reproducing these issues, you can replicate this with the script I leave below in Steps to reproduce :**

![Screenshot from 2023-01-06 20-09-40](https://user-images.githubusercontent.com/5216968/211114823-9c60d341-ed5b-4daa-b507-5b9e38eb2266.png)

All 9 files are different from each other.

**1st issue:**
I could reproduce #3152  and I went further so I found 3 more issues related to this one.

This video shows the stuck process while trying to move.

https://user-images.githubusercontent.com/5216968/211820523-86e99af9-ee2f-4143-8de2-feecd7108bf3.mp4

**2nd issue:**

After moving all files from dir_2 to dir_1 and selecting "Duplicate" to solve the conflict, the undo operation effectively moves the files back to dir_2, but in this particular case the file names after clicking "Undo" are not the original names in dir_2, instead nemo moves them as 'file_1 (copy)', 'file_2 (copy)' and 'file_3 (copy)'.

https://user-images.githubusercontent.com/5216968/211820619-475f1749-c42a-4729-a992-da918dec6895.mp4

**3rd issue:**
Nemo Crashes when I try to undo the last operation after I click the square button (stop) in "Preparing to move 3 files" window.

https://user-images.githubusercontent.com/5216968/211112258-af2daa24-b3b2-4d20-a31a-79e60d076c52.mp4

**4th issue:**
Nemo shows 0 files in a directory when in fact there are 3 of them. Files are created from CLI or Script in this case.
In this video I ran the script "reproduce_bug_in_nemo.sh". I leave it's code below.

https://user-images.githubusercontent.com/5216968/211820766-59c29bf8-2f77-4926-8e9a-8a8d36ebb3c2.mp4

**Steps to reproduce**
First: create directories and files, I wrote this script to make it easier to test issues and to quickly recreate the working scenario.
```
#!/bin/bash

tmp_dir=/tmp/bug_in_nemo
mkdir -vp "${tmp_dir}"/dir_{1,2,3}
cd "${tmp_dir}"
for current_dir in dir_* ; do 
  # Create 3 files inside each dir_*
  # To make it clear that all files have different content I show the md5 hash
  for n in 1 2 3 ; do 
    cat /dev/urandom | tr -dc 'a-z0-9' | head -c $RANDOM >  "${current_dir}"/file_"${n}"
    md5sum "${current_dir}"/file_"${n}"
  done
done
```

Then you can do the same actions I did in videos.

**Expected behavior**

**1st .-** Nemo should determine which number to append after "(copy)",
I think it's better to use the format "_copy_##" rather than the one with parentheses because parenthesis need escaping in CLI, but that's is something minor and a personal opinion.

**2nd .-** Nemo should undo the last move operation using the original file name without the "(copy)" string.

**3rd .-** Nemo should not crash with Segmentation fault (core dumped) error when undoing the move operation.

**4th .-** Nemo should always show the right amount of files inside a directory. Showing 0 erroneously could make the user to believe it's an empty directory and lead them to shift-delete it (It accidentally happened to me btw....)

**Other information**

**Comment by NintendoManiac64** [comment]
I can't help at all with the issues but, just an FYI, your 1st, 2nd, and 4th videos do not show up in the Firefox that is bundled with Mint - I believe this is because those three videos are all encoded with full 4:4:4 chroma while your 3rd video uses the more typical (for video anyway) 4:2:0 chroma subsampling.

**Comment by Neher-Veem** [comment]
@NintendoManiac64 I fixed the problem with 1st, 2nd and 4th videos. Originally I created all of them with Kazam but the only one re-encoded with handbrake was the 3rd one (because it's original size was bigger than github limit) and it seems that was the only one which worked fine, so now I re-uploaded all of them encoded with handbrake. Thanks.

**Comment by Jeremy7701** [comment]
Is this a "move to other pane" error, or would it also occur if you had two separate (single pane) windows?
Sorry, but I haven't tried to reproduce the error.

**Comment by Neher-Veem** [comment]
@Jeremy7701 it happens both in separate windows and in the same one with two panes, same behavior moving and copying

**Comment by NintendoManiac64** [comment]
While I am not OP, I can confirm the second listed issue still exactly occurs as-is in Nemo v6.6.3 (which is also the version that comes bundled with Mint 22.3 Cinnamon).

However, the first listed issue does not occur and therefore the prerequisite scenario for the third issue can no longer be created thereby making the third issue also not occur. I also think the fourth issue does not occur as well from my testing but it being more involved made it more difficult to be 100% certain on if I did things correctly...
