### ISSUE TITLE
When search term entered, column view reverts to default

### ISSUE THREAD

**Issue by rgreen5** [linuxmint/nemo#3249]
### Distribution

Mint 20.1

### Package version

Nemo 4.8.6

### Frequency

Always

### Bug description

When you enter a search term into the Nemo search bar, the column view reverts to a default setting – you lose any extra columns you may have specified in Edit > Preferences. The "custom" columns only return when you close the search bar.

### Steps to reproduce

1. Open the home folder
2. Ensure that the column view shows Name / Size / Date modified / Type / Location.
3. Type a search term in the Nemo search bar

RESULT: The "Location" field disappears. (very inconvenient as the search may return many folders, and without knowing the location, pinpointing the exact folder you want can be trial and error).

The "Location" column only returns when you close the search bar.

### Expected behavior

The customised column view should be maintained throughout.

**Comment by mtwebster** [comment]
This is fixed in 5.0+ - search was substantially reworked, including column layout.

**Comment by bendover22** [comment]
> This is fixed in 5.0+

Update: Then there may be? a regression in Nemo 6.2.8.
In List View, I have many columns enabled.  But Search (for file names) result window  - which replaces the normal List View window - **only** shows 3 columns: **Date modified, Location & Size**.

From the search results window, in Edit > Prefs > "List Columns" still shows all the columns as checked (that show in normal, non-search, "List View" window).  AFAIK, there's no way to customize columns to display in the Search window.

**Comment by mtwebster** [comment]
You can customize the columns for each location (folder) as well as specifically for search. The columns enabled in preferences are only to set the 'default' columns for a folder you've never customized.

You can right-click any of the column headers to customize what columns are shown, and this should be remembered the next time you enter that location, or, in this case, perform another search.

![image](https://github.com/user-attachments/assets/e163a05f-dcb0-4c3b-87b8-0e3f5a5cb20a)
